/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.util.Random;

/**
 *
 * @author Thiago Aguiar
 */
public class frameTelaInicial extends javax.swing.JFrame {

    public frameTelaInicial() {
        
        initComponents();
        lblTextoBalao.setText("<html>Tente descobrir o número no qual estou pensando entre 1 e 6...</html>");
        lblNumeroSorteado.setVisible(false);
        
    }
    
    private Integer sorteiaNumero() {
       
        Random random = new Random();
        int numero = random.nextInt(6); // range de 0 (incluíndo-se) a 6 (excluíndo-se)       
        return numero +1;
        
        /* outra opção de código:
        ** double n = 1 + Math.random() * (7 - 1);
        ** return (int) n; */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnPalpite = new javax.swing.JSpinner();
        lblDigiteSeuPalpite = new javax.swing.JLabel();
        btnVerificaPalpite = new javax.swing.JButton();
        lblNumeroSorteado = new javax.swing.JLabel();
        lblTextoBalao = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setSize(new java.awt.Dimension(150, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnPalpite.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        spnPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        spnPalpite.setMaximumSize(new java.awt.Dimension(30, 30));
        getContentPane().add(spnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 150, 40));

        lblDigiteSeuPalpite.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblDigiteSeuPalpite.setText("Meu palpite:");
        getContentPane().add(lblDigiteSeuPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        btnVerificaPalpite.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnVerificaPalpite.setText("Verificar");
        btnVerificaPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificaPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, 50));

        lblNumeroSorteado.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblNumeroSorteado.setForeground(new java.awt.Color(0, 51, 255));
        lblNumeroSorteado.setText("0");
        getContentPane().add(lblNumeroSorteado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 20, 40));

        lblTextoBalao.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        getContentPane().add(lblTextoBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, 90));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 190, 270));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.jpg"))); // NOI18N
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 320));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Jogo de Adivinhação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificaPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaPalpiteActionPerformed
        
        // SORTEANDO NÚMERO ALEATÓRIO
        int numeroSorteado = sorteiaNumero();
        
        // OBTENDO PALPITE
        int numeroPalpite = Integer.parseInt(spnPalpite.getValue().toString());
        
        // VALIDANDO PALPITE
        if (numeroPalpite == numeroSorteado) {
        
           lblTextoBalao.setText("<html>Você acertou!!! Parabéns!!!</html>");
            
        } else {
            lblTextoBalao.setText("<html>Você errou!!! Eu estava pensando no: " + numeroSorteado + "</html>");
        }
        
    }//GEN-LAST:event_btnVerificaPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificaPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblDigiteSeuPalpite;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblNumeroSorteado;
    private javax.swing.JLabel lblTextoBalao;
    private javax.swing.JSpinner spnPalpite;
    // End of variables declaration//GEN-END:variables
}
